### ISSUE TITLE
gemini wing agents can't work

### ISSUE THREAD

**Issue by guanzeying** [M-J-Murray/MAMEToolkit#21]
I am write agents for gemini wing. my WorkerUtils.py at
GeminiAgents/tensorflow_simple/WorkerUtils.py

def prepro(frames):
    x = []
    for frame in frames: 
        frame = frame[32:214, 12:372]  # crop
        frame = 0.2989 * frame[:, :, 0] + 0.5870 * frame[:, :, 1] + 0.1140 * frame[:, :, 2] # greyscale
        frame = frame[::3, ::3] # downsample
        frame = frame/255
        frame = frame-frame.mean()
        x.append(frame.reshape(1, 61, 120))
    return np.stack(x, axis=3).astype("float32")

When i run agents, I get error:
Traceback (most recent call last):
  File "/home/guanzeying/GeminiAgents/tensorflow_simple/Worker.py", line 55, in run
    observation = wu.prepro(frames)
  File "/home/guanzeying/GeminiAgents/tensorflow_simple/WorkerUtils.py", line 14, in prepro
    x.append(frame.reshape(1, 61, 120))
ValueError: cannot reshape array of size 5002 into shape (1,61,120)

How should I solve this problem?

appendix:
gemini solution:
RGB32 - 32bpp 8-8-8 RGB
width: 256
height: 224

sfiii3n solution:
RGB32 - 32bpp 8-8-8 RGB
width: 384
height: 224

**Comment by guanzeying** [comment]
I wonder why the return value reshape(1, 61, 120). Why?

**Comment by M-J-Murray** [comment]
Please post questions related to [SFAgents](https://github.com/M-J-Murray/SFAgents) in that repository.
The reason you are having issues is because the resolution of gemini is smaller, so the image pre-processing function needs to be adjusted to match that new resolution. This includes the image cropping, downsampling and reshaping.
