### ISSUE TITLE
Environment() setup time seems very long

### ISSUE THREAD

**Issue by dubsand** [M-J-Murray/MAMEToolkit#25]
**Problem:**

When creating any Environment, it takes a significant amount of time to return to code execution while the emulator is already running. 

**Minimal example:**

```python import datetime
import datetime

from MAMEToolkit.sf_environment import Environment

roms_path = 'roms/'
start = datetime.datetime.now()
env = Environment('env1', roms_path)
end = datetime.datetime.now()
print('Time to set up env: {}'.format(end-start))
env.start()
env.close()
```
``` Time to set up env: 0:00:12.894005 ```

In my case, when not throttling, the setup time is much longer than the emulation itself, adding significant overhead to training time. Also, I am forced to reload the save state I am working with in `env.start()` since the emulator has been running for ~13s already.

**Question:**

Is this delay expected behaviour? If not, is there a way to reduce it?

**Comment by M-J-Murray** [comment]
Unfortunately this setup time is normal. This is due to the underlying LUA console being used to interact with MAME. It takes a while to setup all the relevant variables for accessing game data. When I worked on street fighter, the issue of resetting the game was resolved by triggering the "service mode" built into the game, which has a restart button. Restarting the game this way means there is no start up time. So only the initial starting of the game takes 12 seconds.
